/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoemsIndexRouteImport } from './routes/poems.index'
import { Route as PoemsIdRouteImport } from './routes/poems.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoemsIndexRoute = PoemsIndexRouteImport.update({
  id: '/poems/',
  path: '/poems/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoemsIdRoute = PoemsIdRouteImport.update({
  id: '/poems/$id',
  path: '/poems/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/poems/$id': typeof PoemsIdRoute
  '/poems/': typeof PoemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/poems/$id': typeof PoemsIdRoute
  '/poems': typeof PoemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/poems/$id': typeof PoemsIdRoute
  '/poems/': typeof PoemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/poems/$id' | '/poems/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/poems/$id' | '/poems'
  id: '__root__' | '/' | '/poems/$id' | '/poems/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PoemsIdRoute: typeof PoemsIdRoute
  PoemsIndexRoute: typeof PoemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poems/': {
      id: '/poems/'
      path: '/poems'
      fullPath: '/poems/'
      preLoaderRoute: typeof PoemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poems/$id': {
      id: '/poems/$id'
      path: '/poems/$id'
      fullPath: '/poems/$id'
      preLoaderRoute: typeof PoemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PoemsIdRoute: PoemsIdRoute,
  PoemsIndexRoute: PoemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
