/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DhikrRouteImport } from './routes/dhikr'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ShaykhRouteImport } from './routes/shaykh'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'
import { Route as QuranIndexRouteImport } from './routes/quran.index'
import { Route as QuranPagePageRouteImport } from './routes/quran.page.$page'
import { Route as QuranSurahSuraNoRouteImport } from './routes/quran.surah.$suraNo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DhikrRoute = DhikrRouteImport.update({
  id: '/dhikr',
  path: '/dhikr',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ShaykhRoute = ShaykhRouteImport.update({
  id: '/shaykh',
  path: '/shaykh',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranIndexRoute = QuranIndexRouteImport.update({
  id: '/quran/',
  path: '/quran/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranPagePageRoute = QuranPagePageRouteImport.update({
  id: '/quran/page/$page',
  path: '/quran/page/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranSurahSuraNoRoute = QuranSurahSuraNoRouteImport.update({
  id: '/quran/surah/$suraNo',
  path: '/quran/surah/$suraNo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dhikr': typeof DhikrRoute
  '/library': typeof LibraryRoute
  '/shaykh': typeof ShaykhRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/quran/': typeof QuranIndexRoute
  '/quran/page/$page': typeof QuranPagePageRoute
  '/quran/surah/$suraNo': typeof QuranSurahSuraNoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dhikr': typeof DhikrRoute
  '/library': typeof LibraryRoute
  '/shaykh': typeof ShaykhRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/quran': typeof QuranIndexRoute
  '/quran/page/$page': typeof QuranPagePageRoute
  '/quran/surah/$suraNo': typeof QuranSurahSuraNoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dhikr': typeof DhikrRoute
  '/library': typeof LibraryRoute
  '/shaykh': typeof ShaykhRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/quran/': typeof QuranIndexRoute
  '/quran/page/$page': typeof QuranPagePageRoute
  '/quran/surah/$suraNo': typeof QuranSurahSuraNoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dhikr'
    | '/library'
    | '/shaykh'
    | '/books/$bookId'
    | '/quran/'
    | '/quran/page/$page'
    | '/quran/surah/$suraNo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dhikr'
    | '/library'
    | '/shaykh'
    | '/books/$bookId'
    | '/quran'
    | '/quran/page/$page'
    | '/quran/surah/$suraNo'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dhikr'
    | '/library'
    | '/shaykh'
    | '/books/$bookId'
    | '/quran/'
    | '/quran/page/$page'
    | '/quran/surah/$suraNo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DhikrRoute: typeof DhikrRoute
  LibraryRoute: typeof LibraryRoute
  ShaykhRoute: typeof ShaykhRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
  QuranIndexRoute: typeof QuranIndexRoute
  QuranPagePageRoute: typeof QuranPagePageRoute
  QuranSurahSuraNoRoute: typeof QuranSurahSuraNoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dhikr': {
      id: '/dhikr'
      path: '/dhikr'
      fullPath: '/dhikr'
      preLoaderRoute: typeof DhikrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shaykh': {
      id: '/shaykh'
      path: '/shaykh'
      fullPath: '/shaykh'
      preLoaderRoute: typeof ShaykhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/': {
      id: '/quran/'
      path: '/quran'
      fullPath: '/quran/'
      preLoaderRoute: typeof QuranIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/page/$page': {
      id: '/quran/page/$page'
      path: '/quran/page/$page'
      fullPath: '/quran/page/$page'
      preLoaderRoute: typeof QuranPagePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/surah/$suraNo': {
      id: '/quran/surah/$suraNo'
      path: '/quran/surah/$suraNo'
      fullPath: '/quran/surah/$suraNo'
      preLoaderRoute: typeof QuranSurahSuraNoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DhikrRoute: DhikrRoute,
  LibraryRoute: LibraryRoute,
  ShaykhRoute: ShaykhRoute,
  BooksBookIdRoute: BooksBookIdRoute,
  QuranIndexRoute: QuranIndexRoute,
  QuranPagePageRoute: QuranPagePageRoute,
  QuranSurahSuraNoRoute: QuranSurahSuraNoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
