/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as BookRouteImport } from './routes/book'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoemsIndexRouteImport } from './routes/poems.index'
import { Route as PoemsIdRouteImport } from './routes/poems.$id'

const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoemsIndexRoute = PoemsIndexRouteImport.update({
  id: '/poems/',
  path: '/poems/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoemsIdRoute = PoemsIdRouteImport.update({
  id: '/poems/$id',
  path: '/poems/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/favorites': typeof FavoritesRoute
  '/poems/$id': typeof PoemsIdRoute
  '/poems/': typeof PoemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/favorites': typeof FavoritesRoute
  '/poems/$id': typeof PoemsIdRoute
  '/poems': typeof PoemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/favorites': typeof FavoritesRoute
  '/poems/$id': typeof PoemsIdRoute
  '/poems/': typeof PoemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/book' | '/favorites' | '/poems/$id' | '/poems/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/book' | '/favorites' | '/poems/$id' | '/poems'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/favorites'
    | '/poems/$id'
    | '/poems/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  FavoritesRoute: typeof FavoritesRoute
  PoemsIdRoute: typeof PoemsIdRoute
  PoemsIndexRoute: typeof PoemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poems/': {
      id: '/poems/'
      path: '/poems'
      fullPath: '/poems/'
      preLoaderRoute: typeof PoemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poems/$id': {
      id: '/poems/$id'
      path: '/poems/$id'
      fullPath: '/poems/$id'
      preLoaderRoute: typeof PoemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  FavoritesRoute: FavoritesRoute,
  PoemsIdRoute: PoemsIdRoute,
  PoemsIndexRoute: PoemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
